<?php

namespace Database\Seeders\adminSeeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CityTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
          // ['state_name,country_id] ;
          $indian_cities = [
                                ['Adilabad', 1],
                                ['Adoni', 1],
                                ['Amadalavalasa', 1],
                                ['Amalapuram', 1],
                                ['Anakapalle', 1],
                                ['Anantapur', 1],
                                ['Badepalle', 1],
                                ['Banganapalle', 1],
                                ['Bapatla', 1],
                                ['Bellampalle', 1],
                                ['Bethamcherla', 1],
                                ['Bhadrachalam', 1],
                                ['Bhainsa', 1],
                                ['Bheemunipatnam', 1],
                                ['Bhimavaram', 1],
                                ['Bhongir', 1],
                                ['Bobbili', 1],
                                ['Bodhan', 1],
                                ['Chilakaluripet', 1],
                                ['Chirala', 1],
                                ['Chittoor', 1],
                                ['Cuddapah', 1],
                                ['Devarakonda', 1],
                                ['Dharmavaram', 1],
                                ['Eluru', 1],
                                ['Farooqnagar', 1],
                                ['Gadwal', 1],
                                ['Gooty', 1],
                                ['Gudivada', 1],
                                ['Gudur', 1],
                                ['Guntakal', 1],
                                ['Guntur', 1],
                                ['Hanuman Junction', 1],
                                ['Hindupur', 1],
                                ['Hyderabad', 1],
                                ['Ichchapuram', 1],
                                ['Jaggaiahpet', 1],
                                ['Jagtial', 1],
                                ['Jammalamadugu', 1],
                                ['Jangaon', 1],
                                ['Kadapa', 1],
                                ['Kadiri', 1],
                                ['Kagaznagar', 1],
                                ['Kakinada', 1],
                                ['Kalyandurg', 1],
                                ['Kamareddy', 1],
                                ['Kandukur', 1],
                                ['Karimnagar', 1],
                                ['Kavali', 1],
                                ['Khammam', 1],
                                ['Koratla', 1],
                                ['Kothagudem', 1],
                                ['Kothapeta', 1],
                                ['Kovvur', 1],
                                ['Kurnool', 1],
                                ['Kyathampalle', 1],
                                ['Macherla', 1],
                                ['Machilipatnam', 1],
                                ['Madanapalle', 1],
                                ['Mahbubnagar', 1],
                                ['Mancherial', 1],
                                ['Mandamarri', 1],
                                ['Mandapeta', 1],
                                ['Manuguru', 1],
                                ['Markapur', 1],
                                ['Medak', 1],
                                ['Miryalaguda', 1],
                                ['Mogalthur', 1],
                                ['Nagari', 1],
                                ['Nagarkurnool', 1],
                                ['Nandyal', 1],
                                ['Narasapur', 1],
                                ['Narasaraopet', 1],
                                ['Narayanpet', 1],
                                ['Narsipatnam', 1],
                                ['Nellore', 1],
                                ['Nidadavole', 1],
                                ['Nirmal', 1],
                                ['Nizamabad', 1],
                                ['Nuzvid', 1],
                                ['Ongole', 1],
                                ['Palacole', 1],
                                ['Palasa Kasibugga', 1],
                                ['Palwancha', 1],
                                ['Parvathipuram', 1],
                                ['Pedana', 1],
                                ['Peddapuram', 1],
                                ['Pithapuram', 1],
                                ['Pondur', 1],
                                ['Ponnur', 1],
                                ['Proddatur', 1],
                                ['Punganur', 1],
                                ['Puttur', 1],
                                ['Rajahmundry', 1],
                                ['Rajam', 1],
                                ['Ramachandrapuram', 1],
                                ['Ramagundam', 1],
                                ['Rayachoti', 1],
                                ['Rayadurg', 1],
                                ['Renigunta', 1],
                                ['Repalle', 1],
                                ['Sadasivpet', 1],
                                ['Salur', 1],
                                ['Samalkot', 1],
                                ['Sangareddy', 1],
                                ['Sattenapalle', 1],
                                ['Siddipet', 1],
                                ['Singapur', 1],
                                ['Sircilla', 1],
                                ['Srikakulam', 1],
                                ['Srikalahasti', 1],
                                ['Suryapet', 1],
                                ['Tadepalligudem', 1],
                                ['Tadpatri', 1],
                                ['Tandur', 1],
                                ['Tanuku', 1],
                                ['Tenali', 1],
                                ['Tirupati', 1],
                                ['Tuni', 1],
                                ['Uravakonda', 1],
                                ['Venkatagiri', 1],
                                ['Vicarabad', 1],
                                ['Vijayawada', 1],
                                ['Vinukonda', 1],
                                ['Visakhapatnam', 1],
                                ['Vizianagaram', 1],
                                ['Wanaparthy', 1],
                                ['Warangal', 1],
                                ['Yellandu', 1],
                                ['Yemmiganur', 1],
                                ['Yerraguntla', 1],
                                ['Zahirabad', 1],
                                ['Rajampet', 1],
                                ['Along', 2],
                                ['Bomdila', 2],
                                ['Itanagar', 2],
                                ['Naharlagun', 2],
                                ['Pasighat', 2],
                                ['Abhayapuri', 3],
                                ['Amguri', 3],
                                ['Anandnagaar', 3],
                                ['Barpeta', 3],
                                ['Barpeta Road', 3],
                                ['Bilasipara', 3],
                                ['Bongaigaon', 3],
                                ['Dhekiajuli', 3],
                                ['Dhubri', 3],
                                ['Dibrugarh', 3],
                                ['Digboi', 3],
                                ['Diphu', 3],
                                ['Dispur', 3],
                                ['Gauripur', 3],
                                ['Goalpara', 3],
                                ['Golaghat', 3],
                                ['Guwahati', 3],
                                ['Haflong', 3],
                                ['Hailakandi', 3],
                                ['Hojai', 3],
                                ['Jorhat', 3],
                                ['Karimganj', 3],
                                ['Kokrajhar', 3],
                                ['Lanka', 3],
                                ['Lumding', 3],
                                ['Mangaldoi', 3],
                                ['Mankachar', 3],
                                ['Margherita', 3],
                                ['Mariani', 3],
                                ['Marigaon', 3],
                                ['Nagaon', 3],
                                ['Nalbari', 3],
                                ['North Lakhimpur', 3],
                                ['Rangia', 3],
                                ['Sibsagar', 3],
                                ['Silapathar', 3],
                                ['Silchar', 3],
                                ['Tezpur', 3],
                                ['Tinsukia', 3],
                                ['Amarpur', 4],
                                ['Araria', 4],
                                ['Areraj', 4],
                                ['Arrah', 4],
                                ['Asarganj', 4],
                                ['Aurangabad', 4],
                                ['Bagaha', 4],
                                ['Bahadurganj', 4],
                                ['Bairgania', 4],
                                ['Bakhtiarpur', 4],
                                ['Banka', 4],
                                ['Banmankhi Bazar', 4],
                                ['Barahiya', 4],
                                ['Barauli', 4],
                                ['Barbigha', 4],
                                ['Barh', 4],
                                ['Begusarai', 4],
                                ['Behea', 4],
                                ['Bettiah', 4],
                                ['Bhabua', 4],
                                ['Bhagalpur', 4],
                                ['Bihar Sharif', 4],
                                ['Bikramganj', 4],
                                ['Bodh Gaya', 4],
                                ['Buxar', 4],
                                ['Chandan Bara', 4],
                                ['Chanpatia', 4],
                                ['Chhapra', 4],
                                ['Colgong', 4],
                                ['Dalsinghsarai', 4],
                                ['Darbhanga', 4],
                                ['Daudnagar', 4],
                                ['Dehri-on-Sone', 4],
                                ['Dhaka', 4],
                                ['Dighwara', 4],
                                ['Dumraon', 4],
                                ['Fatwah', 4],
                                ['Forbesganj', 4],
                                ['Gaya', 4],
                                ['Gogri Jamalpur', 4],
                                ['Gopalganj', 4],
                                ['Hajipur', 4],
                                ['Hilsa', 4],
                                ['Hisua', 4],
                                ['Islampur', 4],
                                ['Jagdispur', 4],
                                ['Jamalpur', 4],
                                ['Jamui', 4],
                                ['Jehanabad', 4],
                                ['Jhajha', 4],
                                ['Jhanjharpur', 4],
                                ['Jogabani', 4],
                                ['Kanti', 4],
                                ['Katihar', 4],
                                ['Khagaria', 4],
                                ['Kharagpur', 4],
                                ['Kishanganj', 4],
                                ['Lakhisarai', 4],
                                ['Lalganj', 4],
                                ['Madhepura', 4],
                                ['Madhubani', 4],
                                ['Maharajganj', 4],
                                ['Mahnar Bazar', 4],
                                ['Makhdumpur', 4],
                                ['Maner', 4],
                                ['Manihari', 4],
                                ['Marhaura', 4],
                                ['Masaurhi', 4],
                                ['Mirganj', 4],
                                ['Mokameh', 4],
                                ['Motihari', 4],
                                ['Motipur', 4],
                                ['Munger', 4],
                                ['Murliganj', 4],
                                ['Muzaffarpur', 4],
                                ['Narkatiaganj', 4],
                                ['Naugachhia', 4],
                                ['Nawada', 4],
                                ['Nokha', 4],
                                ['Patna', 4],
                                ['Piro', 4],
                                ['Purnia', 4],
                                ['Rafiganj', 4],
                                ['Rajgir', 4],
                                ['Ramnagar', 4],
                                ['Raxaul Bazar', 4],
                                ['Revelganj', 4],
                                ['Rosera', 4],
                                ['Saharsa', 4],
                                ['Samastipur', 4],
                                ['Sasaram', 4],
                                ['Sheikhpura', 4],
                                ['Sheohar', 4],
                                ['Sherghati', 4],
                                ['Silao', 4],
                                ['Sitamarhi', 4],
                                ['Siwan', 4],
                                ['Sonepur', 4],
                                ['Sugauli', 4],
                                ['Sultanganj', 4],
                                ['Supaul', 4],
                                ['Warisaliganj', 4],
                                ['Ahiwara', 5],
                                ['Akaltara', 5],
                                ['Ambagarh Chowki', 5],
                                ['Ambikapur', 5],
                                ['Arang', 5],
                                ['Bade Bacheli', 5],
                                ['Balod', 5],
                                ['Baloda Bazar', 5],
                                ['Bemetra', 5],
                                ['Bhatapara', 5],
                                ['Bilaspur', 5],
                                ['Birgaon', 5],
                                ['Champa', 5],
                                ['Chirmiri', 5],
                                ['Dalli-Rajhara', 5],
                                ['Dhamtari', 5],
                                ['Dipka', 5],
                                ['Dongargarh', 5],
                                ['Durg-Bhilai Nagar', 5],
                                ['Gobranawapara', 5],
                                ['Jagdalpur', 5],
                                ['Janjgir', 5],
                                ['Jashpurnagar', 5],
                                ['Kanker', 5],
                                ['Kawardha', 5],
                                ['Kondagaon', 5],
                                ['Korba', 5],
                                ['Mahasamund', 5],
                                ['Mahendragarh', 5],
                                ['Mungeli', 5],
                                ['Naila Janjgir', 5],
                                ['Raigarh', 5],
                                ['Raipur', 5],
                                ['Rajnandgaon', 5],
                                ['Sakti', 5],
                                ['Tilda Newra', 5],
                                ['Aldona', 6],
                                ['Curchorem Cacora', 6],
                                ['Madgaon', 6],
                                ['Mapusa', 6],
                                ['Margao', 6],
                                ['Marmagao', 6],
                                ['Panaji', 6],
                                ['Ahmedabad', 7],
                                ['Amreli', 7],
                                ['Anand', 7],
                                ['Ankleshwar', 7],
                                ['Bharuch', 7],
                                ['Bhavnagar', 7],
                                ['Bhuj', 7],
                                ['Cambay', 7],
                                ['Dahod', 7],
                                ['Deesa', 7],
                                ['Dharampur',7],
                                ['Dholka', 7],
                                ['Gandhinagar', 7],
                                ['Godhra', 7],
                                ['Himatnagar', 7],
                                ['Idar', 7],
                                ['Jamnagar', 7],
                                ['Junagadh', 7],
                                ['Kadi', 7],
                                ['Kalavad', 7],
                                ['Kalol', 7],
                                ['Kapadvanj', 7],
                                ['Karjan', 7],
                                ['Keshod', 7],
                                ['Khambhalia', 7],
                                ['Khambhat', 7],
                                ['Kheda', 7],
                                ['Khedbrahma', 7],
                                ['Kheralu', 7],
                                ['Kodinar', 7],
                                ['Lathi', 7],
                                ['Limbdi', 7],
                                ['Lunawada', 7],
                                ['Mahesana', 7],
                                ['Mahuva', 7],
                                ['Manavadar', 7],
                                ['Mandvi', 7],
                                ['Mangrol', 7],
                                ['Mansa', 7],
                                ['Mehmedabad', 7],
                                ['Modasa', 7],
                                ['Morbi', 7],
                                ['Nadiad', 7],
                                ['Navsari', 7],
                                ['Padra', 7],
                                ['Palanpur', 7],
                                ['Palitana', 7],
                                ['Pardi', 7],
                                ['Patan', 7],
                                ['Petlad', 7],
                                ['Porbandar', 7],
                                ['Radhanpur', 7],
                                ['Rajkot', 7],
                                ['Rajpipla', 7],
                                ['Rajula', 7],
                                ['Ranavav', 7],
                                ['Rapar', 7],
                                ['Salaya', 7],
                                ['Sanand', 7],
                                ['Savarkundla', 7],
                                ['Sidhpur', 7],
                                ['Sihor', 7],
                                ['Songadh', 7],
                                ['Surat', 7],
                                ['Talaja', 7],
                                ['Thangadh', 7],
                                ['Tharad', 7],
                                ['Umbergaon', 7],
                                ['Umreth', 7],
                                ['Una', 7],
                                ['Unjha', 7],
                                ['Upleta', 7],
                                ['Vadnagar', 7],
                                ['Vadodara', 7],
                                ['Valsad', 7],
                                ['Vapi', 7],
                                ['Vapi', 7],
                                ['Veraval', 7],
                                ['Vijapur', 7],
                                ['Viramgam', 7],
                                ['Visnagar', 7],
                                ['Vyara', 7],
                                ['Wadhwan', 7],
                                ['Wankaner', 7],
                                ['Adalaj', 7],
                                ['Adityana', 7],
                                ['Alang', 7],
                                ['Ambaji', 7],
                                ['Ambaliyasan', 7],
                                ['Andada', 7],
                                ['Anjar', 7],
                                ['Anklav', 7],
                                ['Antaliya', 7],
                                ['Arambhada', 7],
                                ['Atul', 7],
                                ['Ballabhgarh', 8],
                                ['Ambala', 8],
                                ['Ambala', 8],
                                ['Asankhurd', 8],
                                ['Assandh', 8],
                                ['Ateli', 8],
                                ['Babiyal', 8],
                                ['Bahadurgarh', 8],
                                ['Barwala', 8],
                                ['Bhiwani', 8],
                                ['Charkhi Dadri', 8],
                                ['Cheeka', 8],
                                ['Ellenabad 2', 8],
                                ['Faridabad', 8],
                                ['Fatehabad', 8],
                                ['Ganaur', 8],
                                ['Gharaunda', 8],
                                ['Gohana', 8],
                                ['Gurgaon', 8],
                                ['Haibat(Yamuna Nagar)', 8],
                                ['Hansi', 8],
                                ['Hisar', 8],
                                ['Hodal', 8],
                                ['Jhajjar', 8],
                                ['Jind', 8],
                                ['Kaithal', 8],
                                ['Kalan Wali', 8],
                                ['Kalka', 8],
                                ['Karnal', 8],
                                ['Ladwa', 8],
                                ['Mahendragarh', 8],
                                ['Mandi Dabwali', 8],
                                ['Narnaul', 8],
                                ['Narwana', 8],
                                ['Palwal', 8],
                                ['Panchkula', 8],
                                ['Panipat', 8],
                                ['Pehowa', 8],
                                ['Pinjore', 8],
                                ['Rania', 8],
                                ['Ratia', 8],
                                ['Rewari', 8],
                                ['Rohtak', 8],
                                ['Safidon', 8],
                                ['Samalkha', 8],
                                ['Shahbad', 8],
                                ['Sirsa', 8],
                                ['Sohna', 8],
                                ['Sonipat', 8],
                                ['Taraori', 8],
                                ['Thanesar', 8],
                                ['Tohana', 8],
                                ['Yamunanagar', 8],
                                ['Arki', 9],
                                ['Baddi', 9],
                                ['Bilaspur', 9],
                                ['Chamba', 9],
                                ['Dalhousie', 9],
                                ['Dharamsala', 9],
                                ['Hamirpur', 9],
                                ['Mandi', 9],
                                ['Nahan', 9],
                                ['Shimla', 9],
                                ['Solan', 9],
                                ['Sundarnagar', 9],
                                ['Amlabad', 10],
                                ['Ara', 10],
                                ['Barughutu', 10],
                                ['Bokaro Steel City', 10],
                                ['Chaibasa', 10],
                                ['Chakradharpur', 10],
                                ['Chandrapura', 10],
                                ['Chatra', 10],
                                ['Chirkunda', 10],
                                ['Churi', 10],
                                ['Daltonganj', 10],
                                ['Deoghar', 10],
                                ['Dhanbad', 10],
                                ['Dumka', 10],
                                ['Garhwa', 10],
                                ['Ghatshila', 10],
                                ['Giridih', 10],
                                ['Godda', 10],
                                ['Gomoh', 10],
                                ['Gumia', 10],
                                ['Gumla', 10],
                                ['Hazaribag', 10],
                                ['Hussainabad', 10],
                                ['Jamshedpur', 10],
                                ['Jamtara', 10],
                                ['Jhumri Tilaiya', 10],
                                ['Khunti', 10],
                                ['Lohardaga', 10],
                                ['Madhupur', 10],
                                ['Mihijam', 10],
                                ['Musabani', 10],
                                ['Pakaur', 10],
                                ['Patratu', 10],
                                ['Phusro', 10],
                                ['Ramngarh', 10],
                                ['Ranchi', 10],
                                ['Sahibganj', 10],
                                ['Saunda', 10],
                                ['Simdega', 10],
                                ['Tenu Dam-cum- Kathhara', 10],
                                ['Arasikere', 11],
                                ['Bangalore', 11],
                                ['Belgaum', 11],
                                ['Bellary', 11],
                                ['Chamrajnagar', 11],
                                ['Chikkaballapur', 11],
                                ['Chintamani', 11],
                                ['Chitradurga', 11],
                                ['Chikmagalur', 11],
                                ['Davanagere', 11],
                                ['Dharwad', 11],
                                ['Gadag', 11],
                                ['Gulbarga', 11],
                                ['Gundlupet', 11],
                                ['Hassan', 11],
                                ['Hospet', 11],
                                ['Hubli', 11],
                                ['Karkala', 11],
                                ['Karwar', 11],
                                ['Kolar', 11],
                                ['Kota', 11],
                                ['Lakshmeshwar', 11],
                                ['Lingsugur', 11],
                                ['Maddur', 11],
                                ['Madhugiri', 11],
                                ['Madikeri', 11],
                                ['Magadi', 11],
                                ['Mahalingpur', 11],
                                ['Malavalli', 11],
                                ['Malur', 11],
                                ['Mandya', 11],
                                ['Mangalore', 11],
                                ['Manvi', 11],
                                ['Mudalgi', 11],
                                ['Mudbidri', 11],
                                ['Muddebihal', 11],
                                ['Mudhol', 11],
                                ['Mulbagal', 11],
                                ['Mundargi', 11],
                                ['Mysore', 11],
                                ['Nanjangud', 11],
                                ['Pavagada', 11],
                                ['Puttur', 11],
                                ['Rabkavi Banhatti', 11],
                                ['Raichur', 11],
                                ['Ramanagaram', 11],
                                ['Ramdurg', 11],
                                ['Ranibennur', 11],
                                ['Robertson Pet', 11],
                                ['Ron', 11],
                                ['Sadalgi', 11],
                                ['Sagar', 11],
                                ['Sakleshpur', 11],
                                ['Sandur', 11],
                                ['Sankeshwar', 11],
                                ['Saundatti-Yellamma', 11],
                                ['Savanur', 11],
                                ['Sedam', 11],
                                ['Shahabad', 11],
                                ['Shahpur', 11],
                                ['Shiggaon', 11],
                                ['Shikapur', 11],
                                ['Shimoga', 11],
                                ['Shorapur', 11],
                                ['Shrirangapattana', 11],
                                ['Sidlaghatta', 11],
                                ['Sindgi', 11],
                                ['Sindhnur', 11],
                                ['Sira', 11],
                                ['Sirsi', 11],
                                ['Siruguppa', 11],
                                ['Srinivaspur', 11],
                                ['Talikota', 11],
                                ['Tarikere', 11],
                                ['Tekkalakota', 11],
                                ['Terdal', 11],
                                ['Tiptur', 11],
                                ['Tumkur', 11],
                                ['Udupi', 11],
                                ['Vijayapura', 11],
                                ['Wadi', 11],
                                ['Yadgir', 11],
                                ['Adoor', 12],
                                ['Akathiyoor', 12],
                                ['Alappuzha', 12],
                                ['Ancharakandy', 12],
                                ['Aroor', 12],
                                ['Ashtamichira', 12],
                                ['Attingal', 12],
                                ['Avinissery', 12],
                                ['Chalakudy', 12],
                                ['Changanassery', 12],
                                ['Chendamangalam', 12],
                                ['Chengannur', 12],
                                ['Cherthala', 12],
                                ['Cheruthazham', 12],
                                ['Chittur-Thathamangalam', 12],
                                ['Chockli', 12],
                                ['Erattupetta', 12],
                                ['Guruvayoor', 12],
                                ['Irinjalakuda', 12],
                                ['Kadirur', 12],
                                ['Kalliasseri', 12],
                                ['Kalpetta', 12],
                                ['Kanhangad', 12],
                                ['Kanjikkuzhi', 12],
                                ['Kannur', 12],
                                ['Kasaragod', 12],
                                ['Kayamkulam', 12],
                                ['Kochi', 12],
                                ['Kodungallur', 12],
                                ['Kollam', 12],
                                ['Koothuparamba', 12],
                                ['Kothamangalam', 12],
                                ['Kottayam', 12],
                                ['Kozhikode', 12],
                                ['Kunnamkulam', 12],
                                ['Malappuram', 12],
                                ['Mattannur', 12],
                                ['Mavelikkara', 12],
                                ['Mavoor', 12],
                                ['Muvattupuzha', 12],
                                ['Nedumangad', 12],
                                ['Neyyattinkara', 12],
                                ['Ottappalam', 12],
                                ['Palai', 12],
                                ['Palakkad', 12],
                                ['Panniyannur', 12],
                                ['Pappinisseri', 12],
                                ['Paravoor', 12],
                                ['Pathanamthitta', 12],
                                ['Payyannur', 12],
                                ['Peringathur', 12],
                                ['Perinthalmanna', 12],
                                ['Perumbavoor', 12],
                                ['Ponnani', 12],
                                ['Punalur', 12],
                                ['Quilandy', 12],
                                ['Shoranur', 12],
                                ['Taliparamba', 12],
                                ['Thiruvalla', 12],
                                ['Thiruvananthapuram', 12],
                                ['Thodupuzha', 12],
                                ['Thrissur', 12],
                                ['Tirur', 12],
                                ['Vadakara', 12],
                                ['Vaikom', 12],
                                ['Varkala', 12],
                                ['Ashok Nagar', 13],
                                ['Balaghat', 13],
                                ['Betul', 13],
                                ['Bhopal', 13],
                                ['Burhanpur', 13],
                                ['Chhatarpur', 13],
                                ['Dabra', 13],
                                ['Datia', 13],
                                ['Dewas', 13],
                                ['Dhar', 13],
                                ['Fatehabad', 13],
                                ['Gwalior', 13],
                                ['Indore', 13],
                                ['Itarsi', 13],
                                ['Jabalpur', 13],
                                ['Katni', 13],
                                ['Kotma', 13],
                                ['Lahar', 13],
                                ['Lundi', 13],
                                ['Maharajpur', 13],
                                ['Mahidpur', 13],
                                ['Maihar', 13],
                                ['Malajkhand', 13],
                                ['Manasa', 13],
                                ['Manawar', 13],
                                ['Mandideep', 13],
                                ['Mandla', 13],
                                ['Mandsaur', 13],
                                ['Mauganj', 13],
                                ['Mhow Cantonment', 13],
                                ['Mhowgaon', 13],
                                ['Morena', 13],
                                ['Multai', 13],
                                ['Murwara', 13],
                                ['Nagda', 13],
                                ['Nainpur', 13],
                                ['Narsinghgarh', 13],
                                ['Narsinghgarh', 13],
                                ['Neemuch', 13],
                                ['Nepanagar', 13],
                                ['Niwari', 13],
                                ['Nowgong', 13],
                                ['Nowrozabad', 13],
                                ['Pachore', 13],
                                ['Pali', 13],
                                ['Panagar', 13],
                                ['Pandhurna', 13],
                                ['Panna', 13],
                                ['Pasan', 13],
                                ['Pipariya', 13],
                                ['Pithampur', 13],
                                ['Porsa', 13],
                                ['Prithvipur', 13],
                                ['Raghogarh-Vijaypur', 13],
                                ['Rahatgarh', 13],
                                ['Raisen', 13],
                                ['Rajgarh', 13],
                                ['Ratlam', 13],
                                ['Rau', 13],
                                ['Rehli', 13],
                                ['Rewa', 13],
                                ['Sabalgarh', 13],
                                ['Sagar', 13],
                                ['Sanawad', 13],
                                ['Sarangpur', 13],
                                ['Sarni', 13],
                                ['Satna', 13],
                                ['Sausar', 13],
                                ['Sehore', 13],
                                ['Sendhwa', 13],
                                ['Seoni', 13],
                                ['Seoni-Malwa', 13],
                                ['Shahdol', 13],
                                ['Shajapur', 13],
                                ['Shamgarh', 13],
                                ['Sheopur', 13],
                                ['Shivpuri', 13],
                                ['Shujalpur', 13],
                                ['Sidhi', 13],
                                ['Sihora', 13],
                                ['Singrauli', 13],
                                ['Sironj', 13],
                                ['Sohagpur', 13],
                                ['Tarana', 13],
                                ['Tikamgarh', 13],
                                ['Ujhani', 13],
                                ['Ujjain', 13],
                                ['Umaria', 13],
                                ['Vidisha', 13],
                                ['Wara Seoni', 13],
                                ['Ahmednagar', 14],
                                ['Akola', 14],
                                ['Amravati', 14],
                                ['Aurangabad', 14],
                                ['Baramati', 14],
                                ['Chalisgaon', 14],
                                ['Chinchani', 14],
                                ['Devgarh', 14],
                                ['Dhule', 14],
                                ['Dombivli', 14],
                                ['Durgapur', 14],
                                ['Ichalkaranji', 14],
                                ['Jalna', 14],
                                ['Kalyan', 14],
                                ['Kolhapur', 14],
                                ['Latur', 14],
                                ['Loha', 14],
                                ['Lonar', 14],
                                ['Lonavla', 14],
                                ['Mahad', 14],
                                ['Mahuli', 14],
                                ['Malegaon', 14],
                                ['Malkapur', 14],
                                ['Manchar', 14],
                                ['Mangalvedhe', 14],
                                ['Mangrulpir', 14],
                                ['Manjlegaon', 14],
                                ['Manmad', 14],
                                ['Manwath', 14],
                                ['Mehkar', 14],
                                ['Mhaswad', 14],
                                ['Miraj', 14],
                                ['Morshi', 14],
                                ['Mukhed', 14],
                                ['Mul', 14],
                                ['Mumbai', 14],
                                ['Murtijapur', 14],
                                ['Nagpur', 14],
                                ['Nalasopara', 14],
                                ['Nanded-Waghala', 14],
                                ['Nandgaon', 14],
                                ['Nandura', 14],
                                ['Nandurbar', 14],
                                ['Narkhed', 14],
                                ['Nashik', 14],
                                ['Navi Mumbai', 14],
                                ['Nawapur', 14],
                                ['Nilanga', 14],
                                ['Osmanabad', 14],
                                ['Ozar', 14],
                                ['Pachora', 14],
                                ['Paithan', 14],
                                ['Palghar', 14],
                                ['Pandharkaoda', 14],
                                ['Pandharpur', 14],
                                ['Panvel', 14],
                                ['Parbhani', 14],
                                ['Parli', 14],
                                ['Parola', 14],
                                ['Partur', 14],
                                ['Pathardi', 14],
                                ['Pathri', 14],
                                ['Patur', 14],
                                ['Pauni', 14],
                                ['Pen', 14],
                                ['Phaltan', 14],
                                ['Pulgaon', 14],
                                ['Pune', 14],
                                ['Purna', 14],
                                ['Pusad', 14],
                                ['Rahuri', 14],
                                ['Rajura', 14],
                                ['Ramtek', 14],
                                ['Ratnagiri', 14],
                                ['Raver', 14],
                                ['Risod', 14],
                                ['Sailu', 14],
                                ['Sangamner', 14],
                                ['Sangli', 14],
                                ['Sangole', 14],
                                ['Sasvad', 14],
                                ['Satana', 14],
                                ['Satara', 14],
                                ['Savner', 14],
                                ['Sawantwadi', 14],
                                ['Shahade', 14],
                                ['Shegaon', 14],
                                ['Shendurjana', 14],
                                ['Shirdi', 14],
                                ['Shirpur-Warwade', 14],
                                ['Shirur', 14],
                                ['Shrigonda', 14],
                                ['Shrirampur', 14],
                                ['Sillod', 14],
                                ['Sinnar', 14],
                                ['Solapur', 14],
                                ['Soyagaon', 14],
                                ['Talegaon Dabhade', 14],
                                ['Talode', 14],
                                ['Tasgaon', 14],
                                ['Tirora', 14],
                                ['Tuljapur', 14],
                                ['Tumsar', 14],
                                ['Uran', 14],
                                ['Uran Islampur', 14],
                                ['Wadgaon Road', 14],
                                ['Wai', 14],
                                ['Wani', 14],
                                ['Wardha', 14],
                                ['Warora', 14],
                                ['Warud', 14],
                                ['Washim', 14],
                                ['Yevla', 14],
                                ['Uchgaon', 14],
                                ['Udgir', 14],
                                ['Umarga', 14],
                                ['Umarkhed', 14],
                                ['Umred', 14],
                                ['Vadgaon Kasba', 14],
                                ['Vaijapur', 14],
                                ['Vasai', 14],
                                ['Virar', 14],
                                ['Vita', 14],
                                ['Yavatmal', 14],
                                ['Yawal', 14],
                                ['Imphal', 15],
                                ['Kakching', 15],
                                ['Lilong', 15],
                                ['Mayang Imphal', 15],
                                ['Thoubal', 15],
                                ['Jowai', 16],
                                ['Nongstoin', 16],
                                ['Shillong', 16],
                                ['Tura', 16],
                                ['Aizawl', 17],
                                ['Champhai', 17],
                                ['Lunglei', 17],
                                ['Saiha', 17],
                                ['Dimapur', 18],
                                ['Kohima', 18],
                                ['Mokokchung', 18],
                                ['Tuensang', 18],
                                ['Wokha', 18],
                                ['Zunheboto', 18],
                                ['Anandapur', 19],
                                ['Anugul', 19],
                                ['Asika', 19],
                                ['Balangir', 19],
                                ['Balasore', 19],
                                ['Baleshwar', 19],
                                ['Bamra', 19],
                                ['Barbil', 19],
                                ['Bargarh', 19],
                                ['Bargarh', 19],
                                ['Baripada', 19],
                                ['Basudebpur', 19],
                                ['Belpahar', 19],
                                ['Bhadrak', 19],
                                ['Bhawanipatna', 19],
                                ['Bhuban', 19],
                                ['Bhubaneswar', 19],
                                ['Biramitrapur', 19],
                                ['Brahmapur', 19],
                                ['Brajrajnagar', 19],
                                ['Byasanagar', 19],
                                ['Cuttack', 19],
                                ['Debagarh', 19],
                                ['Dhenkanal', 19],
                                ['Gunupur', 19],
                                ['Hinjilicut', 19],
                                ['Jagatsinghapur', 19],
                                ['Jajapur', 19],
                                ['Jaleswar', 19],
                                ['Jatani', 19],
                                ['Jeypur', 19],
                                ['Jharsuguda', 19],
                                ['Joda', 19],
                                ['Kantabanji', 19],
                                ['Karanjia', 19],
                                ['Kendrapara', 19],
                                ['Kendujhar', 19],
                                ['Khordha', 19],
                                ['Koraput', 19],
                                ['Malkangiri', 19],
                                ['Nabarangapur', 19],
                                ['Paradip', 19],
                                ['Parlakhemundi', 19],
                                ['Pattamundai', 19],
                                ['Phulabani', 19],
                                ['Puri', 19],
                                ['Rairangpur', 19],
                                ['Rajagangapur', 19],
                                ['Raurkela', 19],
                                ['Rayagada', 19],
                                ['Sambalpur', 19],
                                ['Soro', 19],
                                ['Sunabeda', 19],
                                ['Sundargarh', 19],
                                ['Talcher', 19],
                                ['Titlagarh', 19],
                                ['Umarkote', 19],
                                ['Ahmedgarh', 20],
                                ['Amritsar', 20],
                                ['Barnala', 20],
                                ['Batala', 20],
                                ['Bathinda', 20],
                                ['Bhagha Purana', 20],
                                ['Budhlada', 20],
                                ['Chandigarh', 20],
                                ['Dasua', 20],
                                ['Dhuri', 20],
                                ['Dinanagar', 20],
                                ['Faridkot', 20],
                                ['Fazilka', 20],
                                ['Firozpur', 20],
                                ['Firozpur Cantt.', 20],
                                ['Giddarbaha', 20],
                                ['Gobindgarh', 20],
                                ['Gurdaspur', 20],
                                ['Hoshiarpur', 20],
                                ['Jagraon', 20],
                                ['Jaitu', 20],
                                ['Jalalabad', 20],
                                ['Jalandhar', 20],
                                ['Jalandhar Cantt.', 20],
                                ['Jandiala', 20],
                                ['Kapurthala', 20],
                                ['Karoran', 20],
                                ['Kartarpur', 20],
                                ['Khanna', 20],
                                ['Kharar', 20],
                                ['Kot Kapura', 20],
                                ['Kurali', 20],
                                ['Longowal', 20],
                                ['Ludhiana', 20],
                                ['Malerkotla', 20],
                                ['Malout', 20],
                                ['Mansa', 20],
                                ['Maur', 20],
                                ['Moga', 20],
                                ['Mohali', 20],
                                ['Morinda', 20],
                                ['Mukerian', 20],
                                ['Muktsar', 20],
                                ['Nabha', 20],
                                ['Nakodar', 20],
                                ['Nangal', 20],
                                ['Nawanshahr', 20],
                                ['Pathankot', 20],
                                ['Patiala', 20],
                                ['Patran', 20],
                                ['Patti', 20],
                                ['Phagwara', 20],
                                ['Phillaur', 20],
                                ['Qadian', 20],
                                ['Raikot', 20],
                                ['Rajpura', 20],
                                ['Rampura Phul', 20],
                                ['Rupnagar', 20],
                                ['Samana', 20],
                                ['Sangrur', 20],
                                ['Sirhind Fatehgarh Sahib', 20],
                                ['Sujanpur', 20],
                                ['Sunam', 20],
                                ['Talwara', 20],
                                ['Tarn Taran', 20],
                                ['Urmar Tanda', 20],
                                ['Zira', 20],
                                ['Zirakpur', 20],
                                ['Bali', 21],
                                ['Banswara', 21],
                                ['Ajmer', 21],
                                ['Alwar', 21],
                                ['Bandikui', 21],
                                ['Baran', 21],
                                ['Barmer', 21],
                                ['Bikaner', 21],
                                ['Fatehpur', 21],
                                ['Jaipur', 21],
                                ['Jaisalmer', 21],
                                ['Jodhpur', 21],
                                ['Kota', 21],
                                ['Lachhmangarh', 21],
                                ['Ladnu', 21],
                                ['Lakheri', 21],
                                ['Lalsot', 21],
                                ['Losal', 21],
                                ['Makrana', 21],
                                ['Malpura', 21],
                                ['Mandalgarh', 21],
                                ['Mandawa', 21],
                                ['Mangrol', 21],
                                ['Merta City', 21],
                                ['Mount Abu', 21],
                                ['Nadbai', 21],
                                ['Nagar', 21],
                                ['Nagaur', 21],
                                ['Nargund', 21],
                                ['Nasirabad', 21],
                                ['Nathdwara', 21],
                                ['Navalgund', 21],
                                ['Nawalgarh', 21],
                                ['Neem-Ka-Thana', 21],
                                ['Nelamangala', 21],
                                ['Nimbahera', 21],
                                ['Nipani', 21],
                                ['Niwai', 21],
                                ['Nohar', 21],
                                ['Nokha', 21],
                                ['Pali', 21],
                                ['Phalodi', 21],
                                ['Phulera', 21],
                                ['Pilani', 21],
                                ['Pilibanga', 21],
                                ['Pindwara', 21],
                                ['Pipar City', 21],
                                ['Prantij', 21],
                                ['Pratapgarh', 21],
                                ['Raisinghnagar', 21],
                                ['Rajakhera', 21],
                                ['Rajaldesar', 21],
                                ['Rajgarh (Alwar)', 21],
                                ['Rajgarh (Churu', 21],
                                ['Rajsamand', 21],
                                ['Ramganj Mandi', 21],
                                ['Ramngarh', 21],
                                ['Ratangarh', 21],
                                ['Rawatbhata', 21],
                                ['Rawatsar', 21],
                                ['Reengus', 21],
                                ['Sadri', 21],
                                ['Sadulshahar', 21],
                                ['Sagwara', 21],
                                ['Sambhar', 21],
                                ['Sanchore', 21],
                                ['Sangaria', 21],
                                ['Sardarshahar', 21],
                                ['Sawai Madhopur', 21],
                                ['Shahpura', 21],
                                ['Shahpura', 21],
                                ['Sheoganj', 21],
                                ['Sikar', 21],
                                ['Sirohi', 21],
                                ['Sojat', 21],
                                ['Sri Madhopur', 21],
                                ['Sujangarh', 21],
                                ['Sumerpur', 21],
                                ['Suratgarh', 21],
                                ['Taranagar', 21],
                                ['Todabhim', 21],
                                ['Todaraisingh', 21],
                                ['Tonk', 21],
                                ['Udaipur', 21],
                                ['Udaipurwati', 21],
                                ['Vijainagar', 21],
                                ['Gangtok', 22],
                                ['Arakkonam', 23],
                                ['Arcot', 23],
                                ['Aruppukkottai', 23],
                                ['Bhavani', 23],
                                ['Chengalpattu', 23],
                                ['Chennai', 23],
                                ['Chinna salem', 23],
                                ['Coimbatore', 23],
                                ['Coonoor', 23],
                                ['Cuddalore', 23],
                                ['Dharmapuri', 23],
                                ['Dindigul', 23],
                                ['Erode', 23],
                                ['Gudalur', 23],
                                ['Gudalur', 23],
                                ['Gudalur', 23],
                                ['Kanchipuram', 23],
                                ['Karaikudi', 23],
                                ['Karungal', 23],
                                ['Karur', 23],
                                ['Kollankodu', 23],
                                ['Lalgudi', 23],
                                ['Madurai', 23],
                                ['Nagapattinam', 23],
                                ['Nagercoil', 23],
                                ['Namagiripettai', 23],
                                ['Namakkal', 23],
                                ['Nandivaram-Guduvancheri', 23],
                                ['Nanjikottai', 23],
                                ['Natham', 23],
                                ['Nellikuppam', 23],
                                ['Neyveli', 23],
                                ['O Valley', 23],
                                ['Oddanchatram', 23],
                                ['P.N.Patti', 23],
                                ['Pacode', 23],
                                ['Padmanabhapuram', 23],
                                ['Palani', 23],
                                ['Palladam', 23],
                                ['Pallapatti', 23],
                                ['Pallikonda', 23],
                                ['Panagudi', 23],
                                ['Panruti', 23],
                                ['Paramakudi', 23],
                                ['Parangipettai', 23],
                                ['Pattukkottai', 23],
                                ['Perambalur', 23],
                                ['Peravurani', 23],
                                ['Periyakulam', 23],
                                ['Periyasemur', 23],
                                ['Pernampattu', 23],
                                ['Pollachi', 23],
                                ['Polur', 23],
                                ['Ponneri', 23],
                                ['Pudukkottai', 23],
                                ['Pudupattinam', 23],
                                ['Puliyankudi', 23],
                                ['Punjaipugalur', 23],
                                ['Rajapalayam', 23],
                                ['Ramanathapuram', 23],
                                ['Rameshwaram', 23],
                                ['Rasipuram', 23],
                                ['Salem', 23],
                                ['Sankarankoil', 23],
                                ['Sankari', 23],
                                ['Sathyamangalam', 23],
                                ['Sattur', 23],
                                ['Shenkottai', 23],
                                ['Sholavandan', 23],
                                ['Sholingur', 23],
                                ['Sirkali', 23],
                                ['Sivaganga', 23],
                                ['Sivagiri', 23],
                                ['Sivakasi', 23],
                                ['Srivilliputhur', 23],
                                ['Surandai', 23],
                                ['Suriyampalayam', 23],
                                ['Tenkasi', 23],
                                ['Thammampatti', 23],
                                ['Thanjavur', 23],
                                ['Tharamangalam', 23],
                                ['Tharangambadi', 23],
                                ['Theni Allinagaram', 23],
                                ['Thirumangalam', 23],
                                ['Thirunindravur', 23],
                                ['Thiruparappu', 23],
                                ['Thirupuvanam', 23],
                                ['Thiruthuraipoondi', 23],
                                ['Thiruvallur', 23],
                                ['Thiruvarur', 23],
                                ['Thoothukudi', 23],
                                ['Thuraiyur', 23],
                                ['Tindivanam', 23],
                                ['Tiruchendur', 23],
                                ['Tiruchengode', 23],
                                ['Tiruchirappalli', 23],
                                ['Tirukalukundram', 23],
                                ['Tirukkoyilur', 23],
                                ['Tirunelveli', 23],
                                ['Tirupathur', 23],
                                ['Tirupathur', 23],
                                ['Tiruppur', 23],
                                ['Tiruttani', 23],
                                ['Tiruvannamalai', 23],
                                ['Tiruvethipuram', 23],
                                ['Tittakudi', 23],
                                ['Udhagamandalam', 23],
                                ['Udumalaipettai', 23],
                                ['Unnamalaikadai', 23],
                                ['Usilampatti', 23],
                                ['Uthamapalayam', 23],
                                ['Uthiramerur', 23],
                                ['Vadakkuvalliyur', 23],
                                ['Vadalur', 23],
                                ['Vadipatti', 23],
                                ['Valparai', 23],
                                ['Vandavasi', 23],
                                ['Vaniyambadi', 23],
                                ['Vedaranyam', 23],
                                ['Vellakoil', 23],
                                ['Vellore', 23],
                                ['Vikramasingapuram', 23],
                                ['Viluppuram', 23],
                                ['Virudhachalam', 23],
                                ['Virudhunagar', 23],
                                ['Viswanatham', 23],
                                ['Agartala', 24],
                                ['Badharghat', 24],
                                ['Dharmanagar', 24],
                                ['Indranagar', 24],
                                ['Jogendranagar', 24],
                                ['Kailasahar', 24],
                                ['Khowai', 24],
                                ['Pratapgarh', 24],
                                ['Udaipur', 24],
                                ['Achhnera',25],
                                ['Adari',25],
                                ['Agra',25],
                                ['Aligarh',25],
                                ['Allahabad',25],
                                ['Amroha',25],
                                ['Azamgarh',25],
                                ['Bahraich',25],
                                ['Ballia',25],
                                ['Balrampur',25],
                                ['Banda',25],
                                ['Bareilly',25],
                                ['Chandausi',25],
                                ['Dadri',25],
                                ['Deoria',25],
                                ['Etawah',25],
                                ['Fatehabad',25],
                                ['Fatehpur',25],
                                ['Fatehpur',25],
                                ['Greater Noida',25],
                                ['Hamirpur',25],
                                ['Hardoi',25],
                                ['Jajmau',25],
                                ['Jaunpur',25],
                                ['Jhansi',25],
                                ['Kalpi',25],
                                ['Kanpur',25],
                                ['Kota',25],
                                ['Laharpur',25],
                                ['Lakhimpur',25],
                                ['Lal Gopalganj Nindaura',25],
                                ['Lalganj',25],
                                ['Lalitpur',25],
                                ['Lar',25],
                                ['Loni',25],
                                ['Lucknow',25],
                                ['Mathura',25],
                                ['Meerut',25],
                                ['Modinagar',25],
                                ['Muradnagar',25],
                                ['Muzaffarnagar',25],
                                ['Nagina',25],
                                ['Najibabad',25],
                                ['Nakur',25],
                                ['Nanpara',25],
                                ['Naraura',25],
                                ['Naugawan Sadat',25],
                                ['Nautanwa',25],
                                ['Nawabganj',25],
                                ['Nehtaur',25],
                                ['NOIDA',25],
                                ['Noorpur',25],
                                ['Obra',25],
                                ['Orai',25],
                                ['Padrauna',25],
                                ['Palia Kalan',25],
                                ['Parasi',25],
                                ['Phulpur',25],
                                ['Pihani',25],
                                ['Pilibhit',25],
                                ['Pilkhuwa',25],
                                ['Powayan',25],
                                ['Pukhrayan',25],
                                ['Puranpur',25],
                                ['Purquazi',25],
                                ['Purwa',25],
                                ['Rae Bareli',25],
                                ['Rampur',25],
                                ['Rampur Maniharan',25],
                                ['Rasra',25],
                                ['Rath',25],
                                ['Renukoot',25],
                                ['Reoti',25],
                                ['Robertsganj',25],
                                ['Rudauli',25],
                                ['Rudrapur',25],
                                ['Sadabad',25],
                                ['Safipur',25],
                                ['Saharanpur',25],
                                ['Sahaspur',25],
                                ['Sahaswan',25],
                                ['Sahawar',25],
                                ['Sahjanwa',25],
                                ['Saidpur', 25],
                                ['Sambhal',25],
                                ['Samdhan',25],
                                ['Samthar',25],
                                ['Sandi',25],
                                ['Sandila',25],
                                ['Sardhana',25],
                                ['Seohara',25],
                                ['Shahabad', 25],
                                ['Shahabad', 25],
                                ['Shahganj',25],
                                ['Shahjahanpur',25],
                                ['Shamli',25],
                                ['Shamsabad', 25],
                                ['Shamsabad', 25],
                                ['Sherkot',25],
                                ['Shikarpur', 25],
                                ['Shikohabad',25],
                                ['Shishgarh',25],
                                ['Siana',25],
                                ['Sikanderpur',25],
                                ['Sikandra Rao',25],
                                ['Sikandrabad',25],
                                ['Sirsaganj',25],
                                ['Sirsi',25],
                                ['Sitapur',25],
                                ['Soron',25],
                                ['Suar',25],
                                ['Sultanpur',25],
                                ['Sumerpur',25],
                                ['Tanda',25],
                                ['Tanda',25],
                                ['Tetri Bazar',25],
                                ['Thakurdwara',25],
                                ['Thana Bhawan',25],
                                ['Tilhar',25],
                                ['Tirwaganj',25],
                                ['Tulsipur',25],
                                ['Tundla',25],
                                ['Unnao',25],
                                ['Utraula',25],
                                ['Varanasi',25],
                                ['Vrindavan',25],
                                ['Warhapur',25],
                                ['Zaidpur',25],
                                ['Zamania',25],
                                ['Almora', 26],
                                ['Bazpur', 26],
                                ['Chamba', 26],
                                ['Dehradun', 26],
                                ['Haldwani', 26],
                                ['Haridwar', 26],
                                ['Jaspur', 26],
                                ['Kashipur', 26],
                                ['kichha', 26],
                                ['Kotdwara', 26],
                                ['Manglaur', 26],
                                ['Mussoorie', 26],
                                ['Nagla', 26],
                                ['Nainital', 26],
                                ['Pauri', 26],
                                ['Pithoragarh', 26],
                                ['Ramnagar', 26],
                                ['Rishikesh', 26],
                                ['Roorkee', 26],
                                ['Rudrapur', 26],
                                ['Sitarganj', 26],
                                ['Tehri', 26],
                                ['Adra', 27],
                                ['Alipurduar', 27],
                                ['Arambagh', 27],
                                ['Asansol', 27],
                                ['Baharampur', 27],
                                ['Barakar', 27],
                                ['Barasat', 27],
                                ['Bardhaman', 27],
                                ['Bidhan Nagar', 27],
                                ['Chinsura', 27],
                                ['Contai', 27],
                                ['Cooch Behar', 27],
                                ['Darjeeling', 27],
                                ['Durgapur', 27],
                                ['Haldia', 27],
                                ['Howrah', 27],
                                ['Islampur', 27],
                                ['Jhargram', 27],
                                ['Kharagpur', 27],
                                ['Kolkata', 27],
                                ['Mainaguri', 27],
                                ['Mal', 27],
                                ['Mathabhanga', 27],
                                ['Medinipur', 27],
                                ['Memari', 27],
                                ['Monoharpur', 27],
                                ['Murshidabad', 27],
                                ['Nabadwip', 27],
                                ['Naihati', 27],
                                ['Panchla', 27],
                                ['Pandua', 27],
                                ['Paschim Punropara', 27],
                                ['Purulia', 27],
                                ['Raghunathpur', 27],
                                ['Raiganj', 27],
                                ['Rampurhat', 27],
                                ['Ranaghat', 27],
                                ['Sainthia', 27],
                                ['Santipur', 27],
                                ['Siliguri', 27],
                                ['Sonamukhi', 27],
                                ['Srirampore', 27],
                                ['Suri', 27],
                                ['Taki', 27],
                                ['Tamluk', 27],
                                ['Tarakeswar', 27],
                                ['Port Blair',28],
                                ['Amli',29],
                                ['Silvassa',29],
                                ['Daman and Diu', 29],
                                ['Kavaratti',30],
                                ['Asola', 31],
                                ['Delhi', 31],
                                ['Karaikal',32],
                                ['Mahe',32],
                                ['Pondicherry',32],
                                ['Yanam',32],
                                ['Jammu', 33],
                                ['Achabbal', 33],
                                ['Akhnoor', 33],
                                ['Anantnag', 33],
                                ['Arnia', 33],
                                ['Awantipora', 33],
                                ['Bandipore', 33],
                                ['Baramula', 33],
                                ['Kathua', 33],
                                ['Leh', 33],
                                ['Punch', 33],
                                ['Rajauri', 33],
                                ['Sopore', 33],
                                ['Srinagar', 33],
                                ['Udhampur', 33],
        ];


        // Insert states for India
        foreach ($indian_cities as $city) {
            DB::table('city')->insert([
                'city_name' => $city[0],
                'state_id' => $city[1],
                'created_by' => 1,
            ]);
        }
    }
}
